name: Python CI

on:
  push:
    branches:
      - master  # Trigger when a commit is pushed to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests that target the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=$(pwd)/src  # Set the PYTHONPATH to include the src directory
        pytest --maxfail=1 --disable-warnings -q --tb=short

